
trigger:
- main

stages:
- stage: BuildAndTrain
  jobs:
  - job: TrainAndRegister
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'

    - script: |
        pip install -r ci/requirements_ci.txt
        python ci/create_workspace.py
        python ci/train.py
        python ci/model_eval.py
        python ci/register_model.py
      displayName: 'Train and Register Model'

- stage: DeployModel
  dependsOn: BuildAndTrain
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'

    - script: |
        pip install -r cd/requirements_cd.txt
        python cd/deploy.py
      displayName: 'Deploy Model'
